---
title: "Figure 1"
author: "A. Sexton-Oates, E. Mathian, N. Alcala, C. Voegele"
date: "2026-05-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

### Load libraries
```{r}
library(openxlsx)
library(ggplot2)
library(survival)
library(survminer)
library(dplyr)
library(ggbeeswarm)
library(patchwork)
```

### Read data and format 
```{r}
table_S1 <- read.xlsx("Supplementary_Table_S1.xlsx", startRow = 4)
table_S1 <- table_S1[!(is.na(table_S1$`LNET.k.=.4.archetype`)), ]

table_S2 <- read.xlsx("Supplementary_Table_S2.xlsx", startRow = 4)
table_S2 <- table_S2[!(is.na(table_S2$MOFA_LNET_Factor1)), ]

table_S4 <- read.xlsx("Supplementary_Table_S4.xlsx", startRow = 5)
table_S4 <- table_S4[c(1:4),c(9:12)]
table_S4$Factor1 <- as.numeric(table_S4$Factor1)
table_S4$Factor2 <- as.numeric(table_S4$Factor2)
table_S4$Factor5 <- as.numeric(table_S4$Factor5)
table_S4 <- table_S4[,c(2,3,4,1)]

table_S8 <- read.xlsx("Supplementary_Table_s8.xlsx",startRow = 2)
table_S8 <- table_S8[c(1:102),c(1:11)]
for(i in 2:10){
  table_S8[,i] <- as.numeric(table_S8[,i])
}
table_S8$SNVB <- table_S8$SBSB + table_S8$IDB # Add the number of SNVs and Indels together
table_S8$TMB <- log10(table_S8$SNVB+1) # Take the log10+1 of the small variant combined burden for statistics

table_S8$archetype <- sapply(table_S8$sample_id, function(x) table_S1$`LNET.k.=.4.archetype`[which(table_S1$sample.id==x)])

load("HC_sc.RData")

table_S16 <- read.xlsx("Supplementary_Table_S16.xlsx", startRow = 3)

data_1f <- read.csv("Data_Figure1f.csv",header=TRUE,row=1)
```

### Create Figure 1a

```{r}
plot_1a <- merge(table_S1[,c(1,41,46)], table_S2[,c(1,4,5)], by.x="sample.id", by.y="sample_id")
colnames(plot_1a) <- c("sample_id", "supra_carcinoid", "molecular_group", "Factor1", "Factor2")

supra <- plot_1a$sample_id[which(!(is.na(plot_1a$supra_carcinoid)))]

segments_LF12 <- data.frame(x = table_S4$Factor1, y = table_S4$Factor2, xend = table_S4$Factor1[c(2,3,1,1)], yend = table_S4$Factor2[c(2,3,1,1)])
temp <- data.frame(x=table_S4[4,1], y=table_S4[4,2], xend=table_S4$Factor1[2], yend=table_S4$Factor2[2])
segments_LF12 <- rbind(segments_LF12, temp)
temp <- data.frame(x=table_S4[4,1], y=table_S4[4,2], xend=table_S4$Factor1[3], yend=table_S4$Factor2[3])
segments_LF12 <- rbind(segments_LF12, temp)
rm(temp)

ggplot(plot_1a, aes(x=Factor1, y=Factor2, color=molecular_group)) + xlab("Latent Factor 1") + ylab("Latent Factor 2") + 
  geom_point(size = 2.5, alpha = 0.8) +
  geom_point(data=plot_1a[plot_1a$sample_id %in% supra,], pch=21, fill=NA, size=3.5, colour="#7f7f7f", stroke=1) +
  scale_colour_manual(name = "molecular_group", values=c("sc-enriched"="#CC6677","Ca A1"="#999933","Ca B"="#117733","Ca A2"="#DDCC77")) +
  geom_point(data = table_S4, aes(x = Factor1, y = Factor2), size = 1.5, color = "#332288") +
  geom_segment(data = segments_LF12, aes(x = x, y = y, xend = xend, yend = yend), color = "#332288", lineend = "round", linejoin = "round", linewidth = 0.5) +
  theme_classic() + labs(title="ParetoTI fit MOFA LNET \n k=4 over three latent factors (LFs 1, 2 & 5)") + theme(plot.title = element_text(hjust = 0.5))
```


### Create Figure 1b

```{r}
surv_data <- table_S1[,c(1,46,33,34,36,37)]
colnames(surv_data)[2] <- "molecular_group"

surv_data$status <- ifelse(surv_data$census.status=="alive", 1, ifelse(surv_data$census.status=="dead", 2, surv_data$census.status))
surv_data$status <- as.numeric(surv_data$status)
surv_data$time <- surv_data$overall.survival.months
surv_data <- surv_data[!(is.na(surv_data$status)),]
surv_data <- surv_data[!(is.na(surv_data$time)),] # 288 samples
surv_data$time <- as.numeric(surv_data$time)

data_OS_object <- Surv(time = surv_data$time, event = surv_data$status)
fit_OS <- survfit(Surv(time, status) ~ molecular_group, data = surv_data)
ggsurvplot(fit_OS, pval = TRUE, title="Overall survival by molecular group", legend = c(0.75, 0.2), palette=c("#999933","#DDCC77","#117733","#CC6677"), legend.labs = c("Ca A1", "Ca A2", "Ca B","sc-enriched"))
```

### Create Figure 1c
```{r, fig.width=10, fig.height=3.5}
arc4 <- c("Ca A1"="#999933", "Ca A2"="#DDCC77", "Ca B"="#117733", "sc-enriched"="#CC6677") 

p1c1 <- ggplot(data=table_S8, aes(x=archetype, y = SNVB, fill=archetype)) +
  geom_violin(scale = "width", col=NA) + scale_y_log10(limits=c(NA,30000)) +
  geom_boxplot(fill="white", width=0.1) +
  geom_quasirandom(shape=21, col="white",data=table_S8 %>% filter(archetype =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  theme_classic() + ylab("Small variant burden") + xlab("Molecular group") +
  theme(legend.position = "bottom") +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=2,y=20000,yend=20000)) + geom_text(aes(label = "**", y = 21000, x=1.5)) +
  geom_segment(aes(x=2,xend=3,y=11000,yend=11000)) + geom_text(aes(label = "***", y = 12000, x=2.5)) +
  geom_segment(aes(x=2,xend=4,y=15000,yend=15000)) + geom_text(aes(label = "*", y = 16000, x=3)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")

p1c2 <- ggplot(data=table_S8, aes(x=archetype, y = log10(SVB+1), fill=archetype)) +
  geom_violin(scale = "width", col=NA) + geom_boxplot(fill="white", width=0.1) +
  geom_boxplot(fill="white", width=0.1) +
  geom_quasirandom(shape=21, col="white",data=table_S8 %>% filter(archetype =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  coord_cartesian(ylim=c(0,3)) +  scale_y_continuous(breaks=c(0,1,2,3),labels = c(1,10,100,1000)) + 
  theme_classic() + ylab("Structural variant burden") + xlab("Molecular group") +
  theme(legend.position = "bottom") +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=2,y=2.5,yend=2.5)) + geom_text(aes(label = "*", y = 2.55, x=1.5)) +
  geom_segment(aes(x=1,xend=3,y=2.8,yend=2.8)) + geom_text(aes(label = "**", y = 2.85, x=2)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")

p1c3 <- ggplot(data=table_S8[which(table_S8$wholeGenomeDuplication=="FALSE"),], aes(x=archetype, y = prop.del, fill=archetype)) +
  geom_violin(scale = "width", col=NA) + geom_boxplot(fill="white", width=0.1) +
  geom_boxplot(fill="white", width=0.1) +
  geom_quasirandom(shape=21, col="white",data=table_S8 %>% filter(archetype =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  theme_classic() + ylab("Proportion genome deleted") + xlab("Molecular group") +
  theme(legend.position = "bottom") + ylim(c(0,0.41)) + 
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=2,xend=4,y=0.35,yend=0.35)) + geom_text(aes(label = "*", y = 0.36, x=3)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")

patchwork <- p1c1 + p1c2 + p1c3 + plot_layout(ncol=3)
patchwork
```

### Create Figure 1d
```{r}
colour_hallmark <- c("EVADING GROWTH SUPPRESSORS"="#794A1E", "EVADING IMMUNE DESTRUCTION"="#D13995", "GENOME INSTABILITY"="#204393", "REPLICATIVE IMMORTALITY"="#0B7DB0",
                     "REPROGRAMMING ENERGY METABOLISM"="#7F4097", "RESISTING CELL DEATH"="#a4a4a4", "SUSTAINED ANGIOGENESIS"="#EE3D33", "SUSTAINING PROLIFERATIVE SIGNALING"= "#079E58",
                     "TISSUE INVASION AND METASTASIS"="#221E20", "TUMOR-PROMOTING INFLAMMATION"= "#DD7A26")

HC_sc$hallmark_name <- factor(HC_sc$hallmark_name, levels=c("EVADING GROWTH SUPPRESSORS", "EVADING IMMUNE DESTRUCTION", "REPLICATIVE IMMORTALITY", "TUMOR-PROMOTING INFLAMMATION", "TISSUE INVASION AND METASTASIS", "SUSTAINED ANGIOGENESIS", "GENOME INSTABILITY", "RESISTING CELL DEATH", "REPROGRAMMING ENERGY METABOLISM", "SUSTAINING PROLIFERATIVE SIGNALING"))

hallmark_name_format <- c("Suppression \n of growth", "Escaping immune \n response \n to cancer", "Genome instability \n and mutations", "Cell replicative \n immortality", "Change of \n cellular \n energetics", "Escaping \n programmed \n cell death", "Angiogenesis", "Proliferative \n signalling", "Invasion and \n metastasis", "Tumour promoting \n inflammation")

ggplot(HC_sc, aes(x = hallmark_name, y = A, fill = hallmark_name)) +  
  geom_col(position = "identity") +
  geom_text(aes(label = A), color = "white", position = position_stack(vjust = 0.5)) +
  geom_text(aes(label = signif), color = "black", fontface = "bold", position = position_stack(vjust = 1.2, reverse = TRUE), size = 10) +
  scale_fill_manual(values = colour_hallmark) +
  coord_polar(start = 0) +  
  ylim(-700, 500) +
  theme_minimal() +
  theme(legend.position = "none", axis.text.x = element_blank(), axis.text.y = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y = element_blank(),
        axis.title = element_blank(), legend.title = element_blank(), panel.grid.minor = element_line(color = "white", size = 0.5), panel.grid.major = element_line(color = "white", size = 0.5)) +
  guides(fill = guide_legend(nrow = 5, byrow = TRUE)) +
  geom_text(aes(y =  A + 250, label = hallmark_name_format), color = c("#794A1E", "#D13995", "#204393", "#0B7DB0", "#7F4097", "#a4a4a4", "#EE3D33", "#079E58" ,"#221E20", "#DD7A26"), size = 4, hjust = 0.5, angle = 0) +
  geom_text(aes(y = A + 20, label = top_gene), position = position_stack(vjust = -1), size = 3, color = c("#794A1E", "#D13995", "#204393", "#0B7DB0", "#7F4097", "#a4a4a4", "#EE3D33", "#079E58" ,"#221E20", "#DD7A26"))
```

### Create Figure 1e
```{r}
plot_df_1e <- as.data.frame(table(table_S16$`Molecular.group/tumour.type`, table_S16$Cluster.label))
plot_df_1e$Var1 <- factor(plot_df_1e$Var1, levels=c("Ca A1","Ca A2","Ca B","sc-enriched","LCNEC","SCLC","LUAD","LUSC"))
plot_df_1e$Var2 <- factor(plot_df_1e$Var2, levels=c("Immune_rich","Immune_stromal","Immune_desert","Immune_stroma_desert"))

immarc6 <- c(Immune_rich="red", Immune_stromal="darkgreen", Immune_desert="yellow", Immune_stroma_desert="orange")

ggplot(plot_df_1e, aes(x=Var1,y=Freq,fill=Var2)) + 
  geom_bar(stat="identity", position = "fill") + 
  theme_classic() + theme(axis.text.x = element_text(angle=90,hjust=1,vjust=0.5),axis.title.x = element_blank()) + 
  scale_fill_manual(values=immarc6) + ylab("Proportion")

```

### Create Figure 1f
```{r, fig.width=10, fig.height=5}
arc9 <- c("lung NETs Ca A1"="#999933", "lung NETs Ca A2"="#DDCC77", "lung NETs Ca B"="#117733", "lung NETs supra-carcinoids"="#CC6677", "LCNEC"="#882255", "SCLC"="#332288", 
          "rectum NETs"="#33D6FF", "pancreas NETs"="#909090", "small intestine NETs"="#E5191C")
  
ggplot(data_1f, aes(x = UMAP1 , y = UMAP2, color = Group)) +
  geom_point(size=2.5, alpha=0.8) + scale_colour_manual(values=arc9) +
  xlab("UMAP dimension 1") + ylab("UMAP dimension 2") + theme_classic()
```

### Create Figure 1g















