---
title: "Fig. 4f left panel"
author: "Alexandra Sexton-Oates"
date: "2025-08-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

#### Load libraries
```{r}
library(openxlsx)
library(ggplot2)
library(ggbeeswarm)
```

#### Load data
```{r}
expr_data <- read.xlsx("Data_Figure4f_left.xlsx")
```

#### Statistical tests
```{r}
summary(aov(ICAM1_vst ~ archetype_2, data = expr_data[which(!(is.na(expr_data$archetype))),]))[[1]][1,5]

t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A1", "Ca A2"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A1", "Ca A2"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A1", "Ca B"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A1", "Ca B"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A1", "sc-enriched"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A1", "sc-enriched"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A1", "LCNEC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A1", "LCNEC"))], alternative = "two.sided")$p.value 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A1", "SCLC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A1", "SCLC"))], alternative = "two.sided") 

t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A2", "Ca B"))] ~  
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A2", "Ca B"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A2", "sc-enriched"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A2", "sc-enriched"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A2", "LCNEC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A2", "LCNEC"))], alternative = "two.sided")$p.value 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca A2", "SCLC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca A2", "SCLC"))], alternative = "two.sided")

t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca B", "sc-enriched"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca B", "sc-enriched"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca B", "LCNEC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca B", "LCNEC"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("Ca B", "SCLC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("Ca B", "SCLC"))], alternative = "two.sided") 

t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("sc-enriched", "LCNEC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("sc-enriched", "LCNEC"))], alternative = "two.sided") 
t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("sc-enriched", "SCLC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("sc-enriched", "SCLC"))], alternative = "two.sided") 

t.test(expr_data$ICAM1_vst[which(expr_data$archetype_2 %in% c("LCNEC", "SCLC"))] ~ 
         expr_data$archetype_2[which(expr_data$archetype_2 %in% c("LCNEC", "SCLC"))], alternative = "two.sided") 
```

#### Plot
#### Include tests for sc-enriched versus Ca A1, Ca A2, Ca B, LCNEC, and SCLC 
```{r}
expr_data$archetype_2 <- factor(expr_data$archetype_2, levels=c("Ca A1","Ca A2","Ca B","sc-enriched","LCNEC","SCLC"))

ggplot(expr_data, aes(x=archetype_2, y=ICAM1_log_TPM, fill=archetype_2)) +
  geom_violin(scale = "width") + 
  geom_boxplot(fill="white", width=0.1, outlier.size = 0.4) +
  geom_quasirandom(shape=21, col="white",data=expr_data[which(expr_data$archetype_2=="sc-enriched"),]) +
  scale_fill_manual(name = "Archetype/Type", values=c("Ca A1"="#999933", "Ca A2"="#DDCC77", "Ca B"="#117733", "sc-enriched"="#CC6677", "LCNEC"="#882255", "SCLC"="#332288")) +
  geom_hline(yintercept = log10(1+1), linetype="dashed") +
  theme_classic() + ylab("ICAM1 expression (log10(tpm + 1))") + xlab("Molecular group/Type") + 
  theme(legend.position = "bottom") +
  scale_y_continuous(breaks = c(0,1,2,3), limits=c(0,4.5)) +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=4,y=3,yend=3)) +  geom_text(aes(label = "***", y = 3.1, x=2.5)) +
  geom_segment(aes(x=2,xend=4,y=3.3,yend=3.3)) +  geom_text(aes(label = "***", y = 3.4, x=3)) +
  geom_segment(aes(x=3,xend=4,y=3.6,yend=3.6)) +  geom_text(aes(label = "***", y = 3.7, x=3.5)) +
  geom_segment(aes(x=5,xend=4,y=3.9,yend=3.9)) +  geom_text(aes(label = "***", y = 4, x=4.5)) +
  geom_segment(aes(x=6,xend=4,y=4.2,yend=4.2)) +  geom_text(aes(label = "***", y = 4.3, x=5)) +
  geom_text(aes(label = "P value = 6.02 x10-16, ANOVA", y = 4.5, x=2)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")
```
