---
title: "Extended Data Fig. 3a,b,c,d,f,g,h"
author: "Alexandra Sexton-Oates"
date: "08/08/2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```


### Load libraries
```{r}
library(openxlsx)
library(RColorBrewer)
library(circlize)
library(ComplexHeatmap)
library(ggplot2)
library(ggradar)
library(ggbeeswarm)
library(dplyr)
```

### Read datasets
```{r}
table_S1 <- read.xlsx("Supplementary_Table_S1.xlsx", startRow = 4) # sample information 
NE_expr_data <- read.xlsx("Data_ExtendedDataFigure_3a.xlsx") # vst expression values for neuroendocrine genes
bdh_expr_data <- read.xlsx("Data_ExtendedDataFigure_3bdh.xlsx") # vst and tpm expression values for DLL3, NKX2-1, and TERT
c_expr_data <- read.xlsx("Data_ExtendedDataFigure_3c.xlsx") # tpm expression values for radar plot
fg_expr_data <- read.xlsx("Data_ExtendedDataFigure_3fg.xlsx") # expression data values for SCLC subtypes

arc4 <- c("Ca A1"="#999933", "Ca A2"="#DDCC77", "Ca B"="#117733", "sc-enriched"="#CC6677")
```


### ED Fig. 3a

#### Format data
```{r}
NE_expr_data <- data.frame(NE_expr_data[,-1], row.names=NE_expr_data[,1])

clin_var <- table_S1[which(table_S1$sample.id %in% rownames(NE_expr_data)), c(1,47)]
colnames(clin_var) <- c("sample_id", "molecular_group")
clin_var <- clin_var[order(match(clin_var$sample_id, rownames(NE_expr_data))),]
all(rownames(NE_expr_data)==clin_var$sample_id) 
```

#### Scale expression data 
```{r}
NE_vst_z <- scale(NE_expr_data, center = TRUE, scale = TRUE) 
NE_vst_z[NE_vst_z > 2] <- 2
NE_vst_z[NE_vst_z < -2] <- -2
NE_vst_z <- t(NE_vst_z)
all(colnames(NE_vst_z)==clin_var$sample_id) 
```

#### Make heatmap
```{r}
color_ranges <- c(RColorBrewer::brewer.pal(9,"RdBu")[9], "white" , RColorBrewer::brewer.pal(9,"RdBu")[1])
col_fun <- colorRamp2(c(-2, 0, 2),color_ranges)

ha <- ComplexHeatmap::HeatmapAnnotation(
  'Molecular group' = clin_var$molecular_group,
  col = list('Molecular group' = c("Ca A1"="#999933", "Ca A2"="#DDCC77","Ca B"="#117733","sc-enriched"="#CC6677")
  )
)

ComplexHeatmap::Heatmap(NE_vst_z, col = col_fun, top_annotation = ha, show_column_names = FALSE, row_names_gp = gpar(fontsize = 5))
```


### ED Fig. 3b

#### Statistical tests
```{r}
summary(aov(DLL3_vst ~ molecular_group, data = bdh_expr_data))[[1]][1,5] 

t.test(bdh_expr_data$DLL3_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))], alternative = "two.sided")$p.value 
t.test(bdh_expr_data$DLL3_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca B"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca B"))], alternative = "two.sided")$p.value 
t.test(bdh_expr_data$DLL3_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))], alternative = "two.sided") 
t.test(bdh_expr_data$DLL3_vst[which(bdh_expr_data$molecular_group %in% c("Ca A2", "Ca B"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A2", "Ca B"))], alternative = "two.sided") 
t.test(bdh_expr_data$DLL3_vst[which(bdh_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))], alternative = "two.sided") 
t.test(bdh_expr_data$DLL3_vst[which(bdh_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))], alternative = "two.sided") 
```

#### Plot 
```{r}
ggplot(data=bdh_expr_data, aes(x=molecular_group, y = log10(DLL3_tpm+1), fill=molecular_group)) +
  geom_violin(scale = "width") + 
  geom_boxplot(fill="white", width=0.1, outlier.size = 0.4) +
  geom_quasirandom(shape=21, col="white",data=bdh_expr_data %>% filter(molecular_group =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  geom_hline(yintercept = log10(1+1), linetype="dashed") +
  theme_classic() + ylab("DLL3 expression [log10(TPM+1)]") + xlab("Molecular group") +
  theme(legend.position = "bottom") +
  scale_y_continuous(breaks = c(0,0.5,1,1.5,2,2.5), limits=c(0,3.5)) +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=2,y=2.5,yend=2.5)) + geom_text(aes(label = "***", y = 2.6, x=1.5)) +
  geom_segment(aes(x=1,xend=3,y=2.8,yend=2.8)) + geom_text(aes(label = "***", y = 2.9, x=2)) +
  geom_segment(aes(x=1,xend=4,y=3.1,yend=3.1)) + geom_text(aes(label = "*", y = 3.2, x=2.5)) +
  geom_text(aes(label = "P value = 1.14 x10-32, ANOVA", y = 3.5, x=2)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")
```


### ED Fig. 3c

#### Format data
```{r}
c_expr_data <- read.xlsx("Data_ExtendedDataFigure_3c.xlsx")

c_expr_data$FGFR3_log <- log10(c_expr_data$FGFR3 +1)
c_expr_data$HNF4A_log <- log10(c_expr_data$HNF4A +1)
c_expr_data$HNF1A_log <- log10(c_expr_data$HNF1A +1)
c_expr_data$FGFR4_log <- log10(c_expr_data$FGFR4 +1)
c_expr_data$FOXA3_log <- log10(c_expr_data$FOXA3 +1)

c_expr_data_radar <- aggregate(c_expr_data[,c(8:12)], list(c_expr_data$molecular_group), mean)
colnames(c_expr_data_radar) <- c("group", "FGFR3", "HNF4A", "HNF1A", "FGFR4", "FOXA3")
c_expr_data_radar <- c_expr_data_radar[,c(1,4,3,6,2,5)]

min(c_expr_data_radar[,c(2:6)]) # To add to plot - min line
max(c_expr_data_radar[,c(2:6)]) # To add to plot - max line
```

#### Plot
```{r}
ggradar(c_expr_data_radar, 
        group.colours = c("Ca A1" = "#999933", "Ca A2" = "#DDCC77", "Ca B" = "#117733", "sc-enriched" = "#CC6677"), 
        group.line.width = 1, 
        group.point.size = 1.5,
        background.circle.colour = "white",
        gridline.mid.colour = "grey",
        axis.label.size = 4,  
        grid.label.size = 4, 
        legend.position = "bottom")
```


### ED Fig. 3d

#### Statistical tests 
```{r}
summary(aov(NKX2_1_vst ~ molecular_group, data = bdh_expr_data))[[1]][1,5] 

t.test(bdh_expr_data$NKX2_1_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))], alternative = "two.sided")$p.value 
t.test(bdh_expr_data$NKX2_1_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca B"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca B"))], alternative = "two.sided")$p.value 
t.test(bdh_expr_data$NKX2_1_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))], alternative = "two.sided") 
t.test(bdh_expr_data$NKX2_1_vst[which(bdh_expr_data$molecular_group %in% c("Ca A2", "Ca B"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A2", "Ca B"))], alternative = "two.sided") 
t.test(bdh_expr_data$NKX2_1_vst[which(bdh_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))], alternative = "two.sided")
t.test(bdh_expr_data$NKX2_1_vst[which(bdh_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))], alternative = "two.sided") 
```

#### Plot
```{r}
ggplot(data=bdh_expr_data, aes(x=molecular_group, y = log10(NKX2_1_tpm+1), fill=molecular_group)) +
  geom_violin(scale = "width") + 
  geom_boxplot(fill="white", width=0.1, outlier.size = 0.4) +
  geom_quasirandom(shape=21, col="white",data=bdh_expr_data %>% filter(molecular_group =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  geom_hline(yintercept = log10(1+1), linetype="dashed") +
  theme_classic() + ylab("NKX2-1 expression [log10(TPM+1)]") + xlab("Molecular group") +
  theme(legend.position = "bottom") +
  scale_y_continuous(breaks = c(0,1,2,3), limits=c(0,4.5)) +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=2,y=3.0,yend=3.0)) + geom_text(aes(label = "***", y = 3.1, x=1.5)) +
  geom_segment(aes(x=1,xend=3,y=3.3,yend=3.3)) + geom_text(aes(label = "***", y = 3.4, x=2)) +
  geom_segment(aes(x=2,xend=3,y=3.6,yend=3.6)) + geom_text(aes(label = "***", y = 3.7, x=2.5)) +
  geom_segment(aes(x=2,xend=4,y=3.9,yend=3.9)) + geom_text(aes(label = "**", y = 4.0, x=3)) +
  geom_segment(aes(x=3,xend=4,y=3.0,yend=3.0)) + geom_text(aes(label = "***", y = 3.1, x=3.5)) +
  geom_text(aes(label = "P value = 8.24 x10-46, ANOVA", y = 4.5, x=2)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")
```


### ED Fig. 3f

#### Format data
```{r}
f_expr_data <- fg_expr_data[,c(1,3:6)]
f_expr_data <- data.frame(f_expr_data[,-1], row.names=f_expr_data[,1])

f_expr_data$ASCL1_tpm <- log10(f_expr_data$ASCL1_tpm + 1)
f_expr_data$NEUROD1_tpm <- log10(f_expr_data$NEUROD1_tpm + 1)
f_expr_data$POU2F3_tpm <- log10(f_expr_data$POU2F3_tpm + 1)
f_expr_data$I_score_tpm <- log10(f_expr_data$I_score_tpm + 1)

clin_var <- clin_var[order(clin_var$molecular_group), ]
clin_var <- clin_var[order(clin_var$molecular_group, clin_var$sample_id), ]

f_expr_data <- f_expr_data[order(match(rownames(f_expr_data), clin_var$sample_id)), ]
all(rownames(f_expr_data)==clin_var$sample_id)
f_expr_data <- t(as.matrix(f_expr_data))
```

#### Create heatmap
```{r}
color_ranges <- c(RColorBrewer::brewer.pal(9,"RdBu")[9], "white" , RColorBrewer::brewer.pal(9,"RdBu")[1])

ha <- ComplexHeatmap::HeatmapAnnotation(
  'Molecular group' = clin_var$molecular_group,
  col = list('Molecular group' = c("Ca A1"="#999933", "Ca A2"="#DDCC77","Ca B"="#117733","sc-enriched"="#CC6677")
  )
)

ComplexHeatmap::Heatmap(f_expr_data, col=circlize::colorRamp2(c(0,1,4),color_ranges), top_annotation = ha, 
                        cluster_columns = FALSE, show_column_names = FALSE, cluster_rows = FALSE, 
                        row_names_gp = gpar(fontsize = 5))
```


### ED Fig. 3g

#### Statistical tests
```{r}
summary(aov(I_score_vst ~ molecular_group, data = fg_expr_data))[[1]][1,5] 

t.test(fg_expr_data$I_score_vst[which(fg_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))] ~ 
         fg_expr_data$molecular_group[which(fg_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))], alternative = "two.sided") 
t.test(fg_expr_data$I_score_vst[which(fg_expr_data$molecular_group %in% c("Ca A1", "Ca B"))] ~ 
         fg_expr_data$molecular_group[which(fg_expr_data$molecular_group %in% c("Ca A1", "Ca B"))], alternative = "two.sided")
t.test(fg_expr_data$I_score_vst[which(fg_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))] ~ 
         fg_expr_data$molecular_group[which(fg_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))], alternative = "two.sided") 
t.test(fg_expr_data$I_score_vst[which(fg_expr_data$molecular_group %in% c("Ca A2", "Ca B"))] ~ 
         fg_expr_data$molecular_group[which(fg_expr_data$molecular_group %in% c("Ca A2", "Ca B"))], alternative = "two.sided") 
t.test(fg_expr_data$I_score_vst[which(fg_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))] ~ 
         fg_expr_data$molecular_group[which(fg_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))], alternative = "two.sided") 
t.test(fg_expr_data$I_score_vst[which(fg_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))] ~ 
         fg_expr_data$molecular_group[which(fg_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))], alternative = "two.sided") 
```

#### Plot
```{r}
ggplot(data=fg_expr_data, aes(x=molecular_group, y = log10(I_score_tpm+1), fill=molecular_group)) +
  geom_violin(scale = "width") + 
  geom_boxplot(fill="white", width=0.1, outlier.size = 0.4) +
  geom_quasirandom(shape=21, col="white",data=fg_expr_data %>% filter(molecular_group =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  geom_hline(yintercept = log10(1+1), linetype="dashed") +
  theme_classic() + ylab("Immune score [log10(mean tpm + 1)]") + xlab("Molecular group") +
  theme(legend.position = "bottom") +
  scale_y_continuous(breaks = c(0,0.5,1.0,1.5,2.0), limits=c(0,2.4)) +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  
  geom_segment(aes(x=1,xend=4,y=1.9,yend=1.9)) + geom_text(aes(label = "***", y = 1.95, x=2.5)) +
  geom_segment(aes(x=2,xend=3,y=1.7,yend=1.7)) + geom_text(aes(label = "*", y = 1.75, x=2.5)) +
  geom_segment(aes(x=2,xend=4,y=2.1,yend=2.1)) + geom_text(aes(label = "***", y = 2.15, x=3)) +
  geom_segment(aes(x=3,xend=4,y=2.3,yend=2.3)) + geom_text(aes(label = "***", y = 2.35, x=3.5)) +
  
  geom_text(aes(label = "P value = 6.01 x10-20, ANOVA", y = 2.4, x=2)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")
```


### ED Fig. 3h 

#### Statistical tests 
```{r}
summary(aov(TERT_vst ~ molecular_group, data = bdh_expr_data))[[1]][1,5]

t.test(bdh_expr_data$TERT_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca A2"))], alternative = "two.sided")
t.test(bdh_expr_data$TERT_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca B"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "Ca B"))], alternative = "two.sided")
t.test(bdh_expr_data$TERT_vst[which(bdh_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A1", "sc-enriched"))], alternative = "two.sided") 
t.test(bdh_expr_data$TERT_vst[which(bdh_expr_data$molecular_group %in% c("Ca A2", "Ca B"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A2", "Ca B"))], alternative = "two.sided") 
t.test(bdh_expr_data$TERT_vst[which(bdh_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca A2", "sc-enriched"))], alternative = "two.sided") 
t.test(bdh_expr_data$TERT_vst[which(bdh_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))] ~ 
         bdh_expr_data$molecular_group[which(bdh_expr_data$molecular_group %in% c("Ca B", "sc-enriched"))], alternative = "two.sided") 
```

#### Plot
```{r}
ggplot(data=bdh_expr_data, aes(x=molecular_group, y = log10(TERT_tpm+1), fill=molecular_group)) +
  geom_violin(scale = "width") + 
  geom_boxplot(fill="white", width=0.1, outlier.size = 0.4) +
  geom_quasirandom(shape=21, col="white",data=bdh_expr_data %>% filter(molecular_group =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  geom_hline(yintercept = log10(1+1), linetype="dashed") +
  theme_classic() + ylab("TERT expression [log10(TPM+1)]") + xlab("Molecular group") +
  theme(legend.position = "bottom") +
  scale_y_continuous(breaks = c(0,0.3,0.6,0.9,1.2), limits=c(0,2.2)) +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=2,y=1.2,yend=1.2)) + geom_text(aes(label = "***", y = 1.25, x=1.5)) +
  geom_segment(aes(x=1,xend=4,y=1.4,yend=1.4)) + geom_text(aes(label = "*", y = 1.45, x=2.5)) +
  geom_segment(aes(x=2,xend=3,y=1.6,yend=1.6)) + geom_text(aes(label = "***", y = 1.65, x=2.5)) +
  geom_segment(aes(x=2,xend=4,y=1.8,yend=1.8)) + geom_text(aes(label = "**", y = 1.85, x=3)) +
  geom_text(aes(label = "P value = 2.95 x10-09, ANOVA", y = 2.2, x=2)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")
```



