---
title: "Figure 6"
author: "A. Sexton-Oates"
date: "2026-06-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

### Load libraries
```{r}
library(openxlsx)
library(ggplot2)
library(ggalluvial)
library(dplyr)
library(ggbeeswarm)
```

### Load data and format
```{r}
tert_class <- read.xlsx("Supplementary_Table_S41.xlsx", startRow = 3)
tert_class <- tert_class[,c(1:11)]

reg_class <- read.xlsx("Supplementary_Table_S42.xlsx", startRow = 3)
reg_class <- reg_class[,c(1:9)]

table_S44 <- read.xlsx("Supplementary_Table_S44.xlsx", startRow = 14)
```

### Create Figure 6b
```{r}
class_data <- merge(reg_class, tert_class, by.x = "Sample.ID", by.y = "sample_id", all.x = TRUE)

alluvial_data <- class_data %>% group_by(`TERT.expression.category.(internal)`, Molecular.group, Regulatory.subtype) %>% summarize(Freq=n())
is_alluvia_form(as.data.frame(alluvial_data), axes = 1:3, silent = TRUE)

colnames(alluvial_data) <- c("TERT_class", "molecular_group", "regulatory_class", "frequency")

alluvial_data$TERT_class <- ifelse(alluvial_data$TERT_class=="low", "TERT_low", "TERT_high")
alluvial_data$TERT_class <- factor(alluvial_data$TERT_class, levels=c("TERT_low","TERT_high"))
alluvial_data$regulatory_class <- factor(alluvial_data$regulatory_class, levels=c("Proneural", "HNF", "Luminal", "Other"))
alluvial_data$molecular_group <- ifelse(alluvial_data$molecular_group=="sc-enriched","sc-e",alluvial_data$molecular_group)

ggplot(as.data.frame(alluvial_data),
       aes(axis1 = TERT_class, axis2 = molecular_group, axis3 = regulatory_class,
           y = frequency,
           fill = molecular_group)) +
  scale_x_discrete(expand = c(.1, .1)) +
  geom_flow() +
  geom_stratum(alpha = .5, fill="white") +
  geom_text(stat = "stratum", size = 3, aes(label = after_stat(stratum))) +
  theme(legend.position = "none") + theme_void() + guides(fill="none") + scale_fill_manual(values=c("Ca A1"="#999933", "Ca A2"="#DDCC77", "Ca B"="#117733", "sc-e"="#CC6677"))
```

### Create Figure 6c
```{r}
table_S44$type <- sapply(table_S44$sample_id, function(x) tert_class$type[which(tert_class$sample_id==x)])

table_S44$signature <- rowMeans(table_S44[,c(20:37)]) # mean of TPM values 

summary(aov(`mean.expression.(vst)` ~ molecular.group, data = table_S44))[[1]][1,5] # 3.907823e-19

t.test(table_S44$`mean.expression.(vst)`[which(table_S44$molecular.group %in% c("Ca A1", "Ca A2"))] ~ 
         table_S44$molecular.group[which(table_S44$molecular.group %in% c("Ca A1", "Ca A2"))], alternative = "two.sided") # p-value = 0.2908
t.test(table_S44$`mean.expression.(vst)`[which(table_S44$molecular.group %in% c("Ca A1", "Ca B"))] ~ 
         table_S44$molecular.group[which(table_S44$molecular.group %in% c("Ca A1", "Ca B"))], alternative = "two.sided") # p-value = 0.0528
t.test(table_S44$`mean.expression.(vst)`[which(table_S44$molecular.group %in% c("Ca A1", "sc-enriched"))] ~ 
         table_S44$molecular.group[which(table_S44$molecular.group %in% c("Ca A1", "sc-enriched"))], alternative = "two.sided") # p-value = 8.216e-09 ***

t.test(table_S44$`mean.expression.(vst)`[which(table_S44$molecular.group %in% c("Ca A2", "Ca B"))] ~ 
         table_S44$molecular.group[which(table_S44$molecular.group %in% c("Ca A2", "Ca B"))], alternative = "two.sided") # p-value = 0.01186 *
t.test(table_S44$`mean.expression.(vst)`[which(table_S44$molecular.group %in% c("Ca A2", "sc-enriched"))] ~ 
         table_S44$molecular.group[which(table_S44$molecular.group %in% c("Ca A2", "sc-enriched"))], alternative = "two.sided") # p-value = 6.018e-10 ***

t.test(table_S44$`mean.expression.(vst)`[which(table_S44$molecular.group %in% c("Ca B", "sc-enriched"))] ~ 
         table_S44$molecular.group[which(table_S44$molecular.group %in% c("Ca B", "sc-enriched"))], alternative = "two.sided") # p-value = 7.08e-09 ***

t.test(table_S44$`mean.expression.(vst)`[which(table_S44$type %in% c("Typical","Atypical"))] ~
         table_S44$type[which(table_S44$type %in% c("Typical","Atypical"))], alternative = "two.sided") # p-value = 0.0002875


arc4 <- c("Ca A1"="#999933", "Ca A2"="#DDCC77", "Ca B"="#117733", "sc-enriched"="#CC6677")
type5 <- c("Typical"="#9DB802","Atypical"="#025B0E","Carcinoid"="#CEDB80","NET G3"="#B89f4AFF", "LCNEC"="#824833","SCLC"="#000000")

ggplot(data=table_S44, aes(x=molecular.group, y = log10(signature+1), fill=molecular.group)) +
  geom_violin(scale = "width") + 
  geom_boxplot(fill="white", width=0.1, outlier.size = 0.4) +
  geom_quasirandom(shape=21, col="white",data=table_S44 %>% filter(molecular.group =="sc-enriched")) +
  scale_fill_manual(name = "Molecular group", values=c(arc4)) +
  theme_classic() + ylab("Prediction signature [log10(mean tpm + 1)]") + xlab("Molecular group") +
  theme(legend.position = "bottom") +
  geom_hline(yintercept = log10(1+1), linetype="dashed") +
  scale_y_continuous(breaks = c(0,0.5,1,1.5,2,2.5,3), limits=c(0,3.9)) +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=4,y=2.8,yend=2.8)) + geom_text(aes(label = "***", y = 2.9, x=2.5)) +
  geom_segment(aes(x=2,xend=3,y=3.1,yend=3.1)) + geom_text(aes(label = "*", y = 3.2, x=2.5)) +
  geom_segment(aes(x=2,xend=4,y=3.4,yend=3.4)) + geom_text(aes(label = "***", y = 3.5, x=3)) +
  geom_segment(aes(x=3,xend=4,y=3.7,yend=3.7)) + geom_text(aes(label = "***", y = 3.8, x=3.5)) +
  geom_text(aes(label = "P value = 3.91 x10-19, ANOVA", y = 3.9, x=2)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")

ggplot(data=table_S44[which(table_S44$type %in% c("Typical","Atypical")),], aes(x=type, y = log10(signature+1), fill=type)) +
  geom_violin(scale = "width") + 
  geom_boxplot(fill="white", width=0.1, outlier.size = 0.4) +
  scale_fill_manual(name = "Tumour type", values=c(type5)) +
  theme_classic() + ylab("Prediction signature [log10(mean tpm + 1)]") + xlab("Tumour type") +
  theme(legend.position = "bottom") +
  geom_hline(yintercept = log10(1+1), linetype="dashed") +
  scale_y_continuous(breaks = c(0,0.5,1,1.5,2,2.5,3), limits=c(0,3.9)) +
  guides(color=guide_legend(nrow=1,byrow=TRUE)) + 
  geom_segment(aes(x=1,xend=2,y=2.8,yend=2.8)) + geom_text(aes(label = "***", y = 2.9, x=1.5)) +
  geom_text(aes(label = "P value = 2.88 x10-4, t-test", y = 3.9, x=1)) +
  theme(axis.text.y=element_text(size=11), axis.text.x=element_text(size=11), 
        axis.title.x=element_text(size=11), axis.title.y=element_text(size=11)) + 
  theme(legend.text=element_text(size=11), legend.title=element_text(size=11)) +
  guides(fill="none")

mean(table_S44$signature[which(table_S44$molecular.group=="Ca A1")]) # 19.32799
mean(table_S44$signature[which(table_S44$molecular.group=="Ca A2")]) # 28.41756
mean(table_S44$signature[which(table_S44$molecular.group=="Ca B")]) # 19.74232
mean(table_S44$signature[which(table_S44$molecular.group=="sc-enriched")]) # 145.437

mean(table_S44$signature[which(table_S44$type=="Typical")]) # 24.39485
mean(table_S44$signature[which(table_S44$type=="Atypical")]) # 40.71967

40/24 # 1.7 fold higher in atypical than typical 
145/28 # 5 fold higher in sc than A2
145/20 # 7 fold higher in sc than A1 or B
```





